### ISSUE TITLE
Draw Path between a POIS and Current location

### ISSUE THREAD

**Issue by niralbhavsar1210** [situmtech/situm-android-getting-started#10]
i am searching for the Solution that how to draw the path between user's current location and one or multiple POI , and Navigate the user on that path.
it is available on Sample app of Google Play store but not on in Any demo.

Waiting for response...

**Comment by adrinieto** [comment]
Hello @niralbhavsar1210,

take a look to the following examples:
* [Show routes between POIs in Google Maps](https://github.com/situmtech/situm-android-getting-started#drawroute) example.
* [Instructions while going from one point to another](https://github.com/situmtech/situm-android-getting-started#guideinstructions)
